server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789

    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1500000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 300000
      leak-detection-threshold: 2000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  cors:
    allowed-origins:
      http://localhost:5173

jwt:
  access:
    expiration: 18000000 #30 minutes to millisecond = 30 * 60 * 1000
    secret: tDZeLB1lCmlfwZ1+fVs9BRquyMtaisf1bWRHbq7WL+w=
  refresh:
    expiration: 1209600000 #14 days to millisecond = 14 * 24 * 60 * 60 * 1000
    secret: S1TZnHDnQS6ojlPYPI+bjd6CXxYhBP/eYmubZsRSANY=